# Creamos el manifiesto para desplegar los pods en el cluster de kubernetes
---
# Deployment de kubernetes con nombre myidp dentro del namespace security
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myidp
  name: myidp
  namespace: security
# Indicamos el numero de replicas de pod a desplegar, el pod que ser치 aplicado con el deployment, la etiqueta del pod
# que se despliega y la imagen de DockerHub que se despliega.
# Con imagePullPolicy: Always estamos indicando que cada vez que kubernetes descarga y lanza un contenedor,
# busca la imagen en el registro (DockerHub)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myidp
  template:
    metadata:
      labels:
        app: myidp
    spec:
      containers:
      - image: awsricardo/pruebacicd:88
        imagePullPolicy: Always
        name: myidp

---
# Creaci칩n del servicio para que los pods se puedan comunicar con el exterior o con otros pods
# El tipo de servicio es Nodeport y el puerto de comunicaci칩n ser치 el 30000
# Se realiza un forward al puerto en el que escucha realmente el pod (8080)

apiVersion: v1
kind: Service
metadata:
  labels:
    app: myidp
  name: myidp
  namespace: security
spec:
  ports:
  - nodePort: 30000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myidp
  type: NodePort

